apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nba-vards
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AZiemelis/nba-vards.git
    targetRevision: main
    path: k8s/nba-vards
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true