apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/AZiemelis/nba-vards.git
    targetRevision: HEAD
    ref: main
  - repoURL: https://prometheus-community.github.io/helm-charts/
    chart: prometheus
    targetRevision: 19.7.2
    helm:
      values: config/prometheus/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
