apiVersion: v2
name: grafana
description: A Helm chart for Grafana
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: grafana
    version: "*"
    repository: "https://grafana.github.io/helm-charts"
